measurements:
  tissue_profile_id: derstine_2022_vat_m205_m51_v1
  tissue_definitions:
    vat_tissue_hu_m205_m51:
      enabled: true
      source_labels: [aVAT, tVAT, VAT]
      hu_range: [-205, -51]
