tissue:
  profile_id: totalsegmentator_optional_200mm3_cleanup_v1
  imat:
    filter_size: true
    filter_size_version: 3D
    filter_size_3D: 200
    filter_size_unit: physical
    filter_size_connectivity: 26
  sm:
    filter_size: true
    filter_size_version: 3D
    filter_size_3D: 200
    filter_size_unit: physical
    filter_size_connectivity: 26
  vat:
    filter_size: true
    filter_size_version: 3D
    filter_size_3D: 200
    filter_size_unit: physical
    filter_size_connectivity: 26
  sat:
    filter_size: true
    filter_size_version: 3D
    filter_size_3D: 200
    filter_size_unit: physical
    filter_size_connectivity: 26
